export const rituals = [
  {
    title: "Ritual of the Dawning Heart",
    filename: "ritual_dawning_heart.png",
    archetype: "Seer",
    phase: "Light – Emergence",
    quote: "With every breath, the horizon brightens within.",
    tags: ["Awakening", "Clarity", "Intention"],
  },
  {
    title: "Ritual of the Golden Thread",
    filename: "ritual_golden_thread.png",
    archetype: "Harmonist",
    phase: "Light – Integration",
    quote: "All things woven in light shall find their rhythm again.",
    tags: ["Connection", "Healing", "Alignment"],
  },
  {
    title: "Ritual of the Veiled Flame",
    filename: "ritual_veiled_flame.png",
    archetype: "Bridgewalker",
    phase: "Neutral – Liminal",
    quote: "Between what was and what shall be, the flame flickers.",
    tags: ["Grounding", "Transition", "Shadow Integration"],
  },
  {
    title: "Ritual of Still Waters",
    filename: "ritual_still_waters.png",
    archetype: "Mirrorkeeper",
    phase: "Neutral – Reflection",
    quote: "In stillness, the unseen becomes clear.",
    tags: ["Clarity", "Reflection", "Balance"],
  },
  {
    title: "Ritual of the Hollow Moon",
    filename: "ritual_hollow_moon.png",
    archetype: "Shadowmancer",
    phase: "Dark – Descent",
    quote: "In silence, the unseen finds its shape.",
    tags: ["Release", "Transformation", "Depth"],
  },
  {
    title: "Ritual of Ash and Ember",
    filename: "ritual_ash_ember.png",
    archetype: "Flamekeeper",
    phase: "Dark – Rebirth",
    quote: "From the ashes of the old, the sacred blaze begins.",
    tags: ["Release", "Power", "Renewal"],
  },
];
